language: python
python: 3.4
sudo: false
env:
  - TOX_ENV=py33
  - TOX_ENV=py34
install:
  - pip install --upgrade pip setuptools tox pytest virtualenv coveralls
script:
  - tox -v -v -e $TOX_ENV
after_success:
  coveralls
